// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HelloWorldOne.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "HelloWorldOne.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define HelloWorldOne_max_cdr_typesize 10000008ULL;
#define HelloWorldOne_max_key_cdr_typesize 0ULL;

HelloWorldOne::HelloWorldOne()
{
    // unsigned long m_index
    m_index = 0;
    // sequence<octet, 10000000> m_points


}

HelloWorldOne::~HelloWorldOne()
{


}

HelloWorldOne::HelloWorldOne(
        const HelloWorldOne& x)
{
    m_index = x.m_index;
    m_points = x.m_points;
}

HelloWorldOne::HelloWorldOne(
        HelloWorldOne&& x) noexcept 
{
    m_index = x.m_index;
    m_points = std::move(x.m_points);
}

HelloWorldOne& HelloWorldOne::operator =(
        const HelloWorldOne& x)
{

    m_index = x.m_index;
    m_points = x.m_points;

    return *this;
}

HelloWorldOne& HelloWorldOne::operator =(
        HelloWorldOne&& x) noexcept
{

    m_index = x.m_index;
    m_points = std::move(x.m_points);

    return *this;
}

bool HelloWorldOne::operator ==(
        const HelloWorldOne& x) const
{

    return (m_index == x.m_index && m_points == x.m_points);
}

bool HelloWorldOne::operator !=(
        const HelloWorldOne& x) const
{
    return !(*this == x);
}

size_t HelloWorldOne::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return HelloWorldOne_max_cdr_typesize;
}

size_t HelloWorldOne::getCdrSerializedSize(
        const HelloWorldOne& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.points().size() > 0)
    {
        current_alignment += (data.points().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }




    return current_alignment - initial_alignment;
}

void HelloWorldOne::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_index;
    scdr << m_points;

}

void HelloWorldOne::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_index;
    dcdr >> m_points;
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void HelloWorldOne::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t HelloWorldOne::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& HelloWorldOne::index()
{
    return m_index;
}

/*!
 * @brief This function copies the value in member points
 * @param _points New value to be copied in member points
 */
void HelloWorldOne::points(
        const std::vector<uint8_t>& _points)
{
    m_points = _points;
}

/*!
 * @brief This function moves the value in member points
 * @param _points New value to be moved in member points
 */
void HelloWorldOne::points(
        std::vector<uint8_t>&& _points)
{
    m_points = std::move(_points);
}

/*!
 * @brief This function returns a constant reference to member points
 * @return Constant reference to member points
 */
const std::vector<uint8_t>& HelloWorldOne::points() const
{
    return m_points;
}

/*!
 * @brief This function returns a reference to member points
 * @return Reference to member points
 */
std::vector<uint8_t>& HelloWorldOne::points()
{
    return m_points;
}


size_t HelloWorldOne::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return HelloWorldOne_max_key_cdr_typesize;
}

bool HelloWorldOne::isKeyDefined()
{
    return false;
}

void HelloWorldOne::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}
