// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HelloWorldOne.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "HelloWorldOne.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>






HelloWorldOne::HelloWorldOne()
{
}

HelloWorldOne::~HelloWorldOne()
{
}

HelloWorldOne::HelloWorldOne(
        const HelloWorldOne& x)
{
    m_index = x.m_index;
    m_points = x.m_points;
}

HelloWorldOne::HelloWorldOne(
        HelloWorldOne&& x) noexcept
{
    m_index = x.m_index;
    m_points = std::move(x.m_points);
}

HelloWorldOne& HelloWorldOne::operator =(
        const HelloWorldOne& x)
{

    m_index = x.m_index;
    m_points = x.m_points;
    return *this;
}

HelloWorldOne& HelloWorldOne::operator =(
        HelloWorldOne&& x) noexcept
{

    m_index = x.m_index;
    m_points = std::move(x.m_points);
    return *this;
}

bool HelloWorldOne::operator ==(
        const HelloWorldOne& x) const
{
    return (m_index == x.m_index &&
           m_points == x.m_points);
}

bool HelloWorldOne::operator !=(
        const HelloWorldOne& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void HelloWorldOne::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t HelloWorldOne::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& HelloWorldOne::index()
{
    return m_index;
}


/*!
 * @brief This function copies the value in member points
 * @param _points New value to be copied in member points
 */
void HelloWorldOne::points(
        const std::vector<uint8_t>& _points)
{
    m_points = _points;
}

/*!
 * @brief This function moves the value in member points
 * @param _points New value to be moved in member points
 */
void HelloWorldOne::points(
        std::vector<uint8_t>&& _points)
{
    m_points = std::move(_points);
}

/*!
 * @brief This function returns a constant reference to member points
 * @return Constant reference to member points
 */
const std::vector<uint8_t>& HelloWorldOne::points() const
{
    return m_points;
}

/*!
 * @brief This function returns a reference to member points
 * @return Reference to member points
 */
std::vector<uint8_t>& HelloWorldOne::points()
{
    return m_points;
}


// Include auxiliary functions like for serializing/deserializing.
#include "HelloWorldOneCdrAux.ipp"

