// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HelloWorldOne.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_HELLOWORLDONE_H_
#define _FAST_DDS_GENERATED_HELLOWORLDONE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(HELLOWORLDONE_SOURCE)
#define HELLOWORLDONE_DllAPI __declspec( dllexport )
#else
#define HELLOWORLDONE_DllAPI __declspec( dllimport )
#endif // HELLOWORLDONE_SOURCE
#else
#define HELLOWORLDONE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define HELLOWORLDONE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima







/*!
 * @brief This class represents the structure HelloWorldOne defined by the user in the IDL file.
 * @ingroup HelloWorldOne
 */
class HelloWorldOne
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport HelloWorldOne();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~HelloWorldOne();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object HelloWorldOne that will be copied.
     */
    eProsima_user_DllExport HelloWorldOne(
            const HelloWorldOne& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object HelloWorldOne that will be copied.
     */
    eProsima_user_DllExport HelloWorldOne(
            HelloWorldOne&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object HelloWorldOne that will be copied.
     */
    eProsima_user_DllExport HelloWorldOne& operator =(
            const HelloWorldOne& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object HelloWorldOne that will be copied.
     */
    eProsima_user_DllExport HelloWorldOne& operator =(
            HelloWorldOne&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x HelloWorldOne object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const HelloWorldOne& x) const;

    /*!
     * @brief Comparison operator.
     * @param x HelloWorldOne object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const HelloWorldOne& x) const;

    /*!
     * @brief This function sets a value in member index
     * @param _index New value for member index
     */
    eProsima_user_DllExport void index(
            uint32_t _index);

    /*!
     * @brief This function returns the value of member index
     * @return Value of member index
     */
    eProsima_user_DllExport uint32_t index() const;

    /*!
     * @brief This function returns a reference to member index
     * @return Reference to member index
     */
    eProsima_user_DllExport uint32_t& index();


    /*!
     * @brief This function copies the value in member points
     * @param _points New value to be copied in member points
     */
    eProsima_user_DllExport void points(
            const std::vector<uint8_t>& _points);

    /*!
     * @brief This function moves the value in member points
     * @param _points New value to be moved in member points
     */
    eProsima_user_DllExport void points(
            std::vector<uint8_t>&& _points);

    /*!
     * @brief This function returns a constant reference to member points
     * @return Constant reference to member points
     */
    eProsima_user_DllExport const std::vector<uint8_t>& points() const;

    /*!
     * @brief This function returns a reference to member points
     * @return Reference to member points
     */
    eProsima_user_DllExport std::vector<uint8_t>& points();

private:

    uint32_t m_index{0};
    std::vector<uint8_t> m_points;

};

#endif // _FAST_DDS_GENERATED_HELLOWORLDONE_H_



